version: '3.8'

services:
  driver:
    build: .
    container_name: Driver12
    environment:
      USER_EMAIL: er@driverandservices.de
      USER_PASSWORD: Hakan2020
      UNTERNEHMEN: driver
      WEBHOOK_ADRESSE: https://bemany-n8n-c1b46415d102.herokuapp.com/webhook/fahrerapp/uber/dispatcher_2
    volumes:
      - ./scripts:/app/scripts
      - ./cookies/:/app/cookies
      - ./screenshots/:/app/screenshots