version: '3.8'

services:
  driver:
    build: .
    container_name: Driver12
    environment:
      USER_EMAIL: er@driverandservices.de
      USER_PASSWORD: Hakan2020
      UNTERNEHMEN: driver
      WEBHOOK_ADRESSE: https://webhook.site/7c3f1b21-041b-4e78-9a27-4adb93b2ec8e
    volumes:
      - ./scripts:/app/scripts
      - ./cookies/:/app/cookies
      - ./screenshots/:/app/screenshots